# ~/.config/starship.toml

[aws]
disabled = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[gcloud]
disabled = true

[git_branch]
style = "bold blue"

[hostname]
# format = "[$ssh_symbol$hostname]($style): "
# ssh_only = false
style = "bold yellow"

[line_break]
# disabled = true

[time]
disabled = false
style = "bold purple"
time_format = "[%T]"
utc_time_offset = "+8"

[username]
# disabled = false
# format = "[$user]($style)@(bold white)"
# show_always = true
style_user = "bold green"
